M48
; DRILL file {KiCad 7.0.8} date 2023 December 13, Wednesday 18:24:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-13T18:24:02-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X7.74Y-52.07
X17.9Y-52.07
T2
X12.82Y-52.07
T0
M30
